#spring Configuration 目前只有一个配置文件,如果有需要,可以分为dev和prod,然后再通过spring.profiles.active=prod 来切换生产或开发环境的配置文件.
spring:
  profiles:
    active: default #控制不同环境的不同配置文件

#Server Configuration
server:
  port: 8077
  context-path: /
#  ssl:
#     key-store: classpath:.keystore
#     key-store-password: 123123
#     key-alias: tomcat

#Logback Configuration 
logging:
   config: classpath:logback.xml

